name: Security Scans
on: [push, pull_request]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
        
      # Nouvelle version de upload-artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
          retention-days: 3  # Optionnel: conserve 3 jours

  nikto-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Nikto Scan
        run: |
          docker run --rm sullo/nikto \
            -h http://localhost:3000 \
            -o ./nikto-report.xml \
            -Format xml
        continue-on-error: true
        
      - name: Upload Nikto Report
        uses: actions/upload-artifact@v4  # Version mise à jour
        with:
          name: nikto-report
          path: ./nikto-report.xml