jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set permissions
        run: |
          mkdir -p .zap
          chmod -R a+r .zap/
          
      - name: Start Node.js server
        run: |
          npm ci
          npm run build
          npm start &  # Lance en arrière-plan
          sleep 10  # Temps pour démarrer
          
      - name: Verify app is running
        run: |
          curl -s http://localhost:3000 || exit 1
          
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          docker_network: 'bridge'
          cmd_options: '-T 60'  # Timeout augmenté
          
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html