name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Nécessaire pour l'intégration GitHub
        with:
          args: >
            -Dsonar.projectKey=38Adrien38_HUST_WebProject
            -Dsonar.organization=Adrien Delaye
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectVersion=1.0
            -Dsonar.sourceEncoding=UTF-8